{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "mirror-db.namespace" . }}
  labels:
    {{- include "mirror-db.labels" . | nindent 4 }}
    name: {{ include "mirror-db.namespace" . }}
{{- end }}

