{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mirror-db.fullname" . }}-pod-labeler
  namespace: {{ include "mirror-db.namespace" . }}
  labels:
    {{- include "mirror-db.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mirror-db.fullname" . }}-pod-labeler-binding
  namespace: {{ include "mirror-db.namespace" . }}
  labels:
    {{- include "mirror-db.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mirror-db.serviceAccountName" . }}
    namespace: {{ include "mirror-db.namespace" . }}
roleRef:
  kind: Role
  name: {{ include "mirror-db.fullname" . }}-pod-labeler
  apiGroup: rbac.authorization.k8s.io
{{- end }}

